In [1]:
import numpy as np
import pandas as pd
import os
from sklearn.utils import class_weight
import pickle
import cv2
import joblib
import lightgbm as lgb
import xgboost as xgb
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import KFold, StratifiedKFold
from imblearn.under_sampling import RandomUnderSampler
from imblearn.over_sampling import RandomOverSampler

In [4]:
data = pd.read_csv('./label.csv')

In [5]:
y = np.array(data['Imagelabel'])
y = np.delete(y, [506, 2040], axis=0)
x = np.load('img_feat_clip.npy')
print(x.shape, y.shape)

(2047, 512) (2047,)


In [6]:
def LR(xtrain,xtest,ytrain,ytest):
    log_model = LogisticRegression()
    log_model.fit(xtrain, ytrain)
    y_pred_log = log_model.predict(xtest)
    print(confusion_matrix(ytest, y_pred_log))
    print(classification_report(ytest,y_pred_log))
def MLP(xtrain,xtest,ytrain,ytest):
    log_model = xgb.XGBClassifier()
    log_model.fit(xtrain, ytrain)
    y_pred_log = log_model.predict(xtest)
    print(confusion_matrix(ytest, y_pred_log))
    print(classification_report(ytest,y_pred_log))
def LGBM(xtrain,xtest,ytrain,ytest):
    lgbm_model = lgb.LGBMClassifier(n_estimators=1000,max_depth=5)
    lgbm_model.fit(xtrain, ytrain)
    y_pred_lgbm = lgbm_model.predict(xtest)
    print(confusion_matrix(ytest, y_pred_lgbm))
    print(classification_report(ytest,y_pred_lgbm))

# No Sampling

In [8]:
kf = StratifiedKFold(n_splits=5, shuffle=True)
for train_index, test_index in kf.split(np.arange(x.shape[0]),y):
    #print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = x[train_index], x[test_index]
    y_train, y_test = y[train_index], y[test_index]
    print('Logistic Regression')
    LR(X_train,X_test,y_train,y_test)
    print('LightGBM')
    LGBM(X_train,X_test,y_train,y_test)

Logistic Regression
[[296  25]
 [ 47  42]]
              precision    recall  f1-score   support

           0       0.86      0.92      0.89       321
           1       0.63      0.47      0.54        89

    accuracy                           0.82       410
   macro avg       0.74      0.70      0.72       410
weighted avg       0.81      0.82      0.81       410

LightGBM
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).


/home/subbainria/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[[311  10]
 [ 60  29]]
              precision    recall  f1-score   support

           0       0.84      0.97      0.90       321
           1       0.74      0.33      0.45        89

    accuracy                           0.83       410
   macro avg       0.79      0.65      0.68       410
weighted avg       0.82      0.83      0.80       410

Logistic Regression
[[278  43]
 [ 50  39]]
              precision    recall  f1-score   support

           0       0.85      0.87      0.86       321
           1       0.48      0.44      0.46        89

    accuracy                           0.77       410
   macro avg       0.66      0.65      0.66       410
weighted avg       0.77      0.77      0.77       410

LightGBM
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).


/home/subbainria/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[[307  14]
 [ 62  27]]
              precision    recall  f1-score   support

           0       0.83      0.96      0.89       321
           1       0.66      0.30      0.42        89

    accuracy                           0.81       410
   macro avg       0.75      0.63      0.65       410
weighted avg       0.79      0.81      0.79       410

Logistic Regression
[[278  42]
 [ 43  46]]
              precision    recall  f1-score   support

           0       0.87      0.87      0.87       320
           1       0.52      0.52      0.52        89

    accuracy                           0.79       409
   macro avg       0.69      0.69      0.69       409
weighted avg       0.79      0.79      0.79       409

LightGBM
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).


/home/subbainria/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[[307  13]
 [ 50  39]]
              precision    recall  f1-score   support

           0       0.86      0.96      0.91       320
           1       0.75      0.44      0.55        89

    accuracy                           0.85       409
   macro avg       0.80      0.70      0.73       409
weighted avg       0.84      0.85      0.83       409

Logistic Regression
[[283  37]
 [ 45  44]]
              precision    recall  f1-score   support

           0       0.86      0.88      0.87       320
           1       0.54      0.49      0.52        89

    accuracy                           0.80       409
   macro avg       0.70      0.69      0.70       409
weighted avg       0.79      0.80      0.80       409

LightGBM
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).


/home/subbainria/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[[312   8]
 [ 62  27]]
              precision    recall  f1-score   support

           0       0.83      0.97      0.90       320
           1       0.77      0.30      0.44        89

    accuracy                           0.83       409
   macro avg       0.80      0.64      0.67       409
weighted avg       0.82      0.83      0.80       409

Logistic Regression
[[294  26]
 [ 49  40]]
              precision    recall  f1-score   support

           0       0.86      0.92      0.89       320
           1       0.61      0.45      0.52        89

    accuracy                           0.82       409
   macro avg       0.73      0.68      0.70       409
weighted avg       0.80      0.82      0.81       409

LightGBM
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).


/home/subbainria/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[[309  11]
 [ 62  27]]
              precision    recall  f1-score   support

           0       0.83      0.97      0.89       320
           1       0.71      0.30      0.43        89

    accuracy                           0.82       409
   macro avg       0.77      0.63      0.66       409
weighted avg       0.81      0.82      0.79       409



# Over-Sampling

In [11]:
for train_index, test_index in kf.split(np.arange(x.shape[0]),y):
    #print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = x[train_index], x[test_index]
    Y_train, Y_test = y[train_index], y[test_index]
    print('Random Over-Sampling')
    ros = RandomOverSampler()
    X_ros, y_ros = ros.fit_resample(X_train, Y_train)
    print('Logistic Regression')
    LR(X_ros,X_test,y_ros,Y_test)
    print('LightGBM')
    LGBM(X_ros,X_test,y_ros,Y_test)

Random Over-Sampling
Logistic Regression
[[254  67]
 [ 42  47]]
              precision    recall  f1-score   support

           0       0.86      0.79      0.82       321
           1       0.41      0.53      0.46        89

    accuracy                           0.73       410
   macro avg       0.64      0.66      0.64       410
weighted avg       0.76      0.73      0.75       410

LightGBM
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).


/home/subbainria/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[[312   9]
 [ 60  29]]
              precision    recall  f1-score   support

           0       0.84      0.97      0.90       321
           1       0.76      0.33      0.46        89

    accuracy                           0.83       410
   macro avg       0.80      0.65      0.68       410
weighted avg       0.82      0.83      0.80       410

Random Over-Sampling
Logistic Regression
[[247  74]
 [ 34  55]]
              precision    recall  f1-score   support

           0       0.88      0.77      0.82       321
           1       0.43      0.62      0.50        89

    accuracy                           0.74       410
   macro avg       0.65      0.69      0.66       410
weighted avg       0.78      0.74      0.75       410

LightGBM
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).


/home/subbainria/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[[305  16]
 [ 58  31]]
              precision    recall  f1-score   support

           0       0.84      0.95      0.89       321
           1       0.66      0.35      0.46        89

    accuracy                           0.82       410
   macro avg       0.75      0.65      0.67       410
weighted avg       0.80      0.82      0.80       410

Random Over-Sampling
Logistic Regression
[[241  79]
 [ 36  53]]
              precision    recall  f1-score   support

           0       0.87      0.75      0.81       320
           1       0.40      0.60      0.48        89

    accuracy                           0.72       409
   macro avg       0.64      0.67      0.64       409
weighted avg       0.77      0.72      0.74       409

LightGBM
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).


/home/subbainria/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[[304  16]
 [ 54  35]]
              precision    recall  f1-score   support

           0       0.85      0.95      0.90       320
           1       0.69      0.39      0.50        89

    accuracy                           0.83       409
   macro avg       0.77      0.67      0.70       409
weighted avg       0.81      0.83      0.81       409

Random Over-Sampling
Logistic Regression
[[255  65]
 [ 32  57]]
              precision    recall  f1-score   support

           0       0.89      0.80      0.84       320
           1       0.47      0.64      0.54        89

    accuracy                           0.76       409
   macro avg       0.68      0.72      0.69       409
weighted avg       0.80      0.76      0.77       409

LightGBM
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).


/home/subbainria/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[[304  16]
 [ 50  39]]
              precision    recall  f1-score   support

           0       0.86      0.95      0.90       320
           1       0.71      0.44      0.54        89

    accuracy                           0.84       409
   macro avg       0.78      0.69      0.72       409
weighted avg       0.83      0.84      0.82       409

Random Over-Sampling
Logistic Regression
[[269  51]
 [ 40  49]]
              precision    recall  f1-score   support

           0       0.87      0.84      0.86       320
           1       0.49      0.55      0.52        89

    accuracy                           0.78       409
   macro avg       0.68      0.70      0.69       409
weighted avg       0.79      0.78      0.78       409

LightGBM
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).


/home/subbainria/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[[311   9]
 [ 56  33]]
              precision    recall  f1-score   support

           0       0.85      0.97      0.91       320
           1       0.79      0.37      0.50        89

    accuracy                           0.84       409
   macro avg       0.82      0.67      0.70       409
weighted avg       0.83      0.84      0.82       409



# Under Sampling

In [12]:
for train_index, test_index in kf.split(np.arange(x.shape[0]),y):
    #print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = x[train_index], x[test_index]
    Y_train, Y_test = y[train_index], y[test_index]
    print('Random Over-Sampling')
    ros = RandomUnderSampler()
    X_ros, y_ros = ros.fit_resample(X_train, Y_train)
    print('Logistic Regression')
    LR(X_ros,X_test,y_ros,Y_test)
    print('LightGBM')
    LGBM(X_ros,X_test,y_ros,Y_test)

Random Over-Sampling
Logistic Regression
[[227  94]
 [ 33  56]]
              precision    recall  f1-score   support

           0       0.87      0.71      0.78       321
           1       0.37      0.63      0.47        89

    accuracy                           0.69       410
   macro avg       0.62      0.67      0.63       410
weighted avg       0.76      0.69      0.71       410

LightGBM
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).


/home/subbainria/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[[250  71]
 [ 32  57]]
              precision    recall  f1-score   support

           0       0.89      0.78      0.83       321
           1       0.45      0.64      0.53        89

    accuracy                           0.75       410
   macro avg       0.67      0.71      0.68       410
weighted avg       0.79      0.75      0.76       410

Random Over-Sampling
Logistic Regression
[[232  89]
 [ 26  63]]
              precision    recall  f1-score   support

           0       0.90      0.72      0.80       321
           1       0.41      0.71      0.52        89

    accuracy                           0.72       410
   macro avg       0.66      0.72      0.66       410
weighted avg       0.79      0.72      0.74       410

LightGBM
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).


/home/subbainria/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[[226  95]
 [ 20  69]]
              precision    recall  f1-score   support

           0       0.92      0.70      0.80       321
           1       0.42      0.78      0.55        89

    accuracy                           0.72       410
   macro avg       0.67      0.74      0.67       410
weighted avg       0.81      0.72      0.74       410

Random Over-Sampling
Logistic Regression
[[217 103]
 [ 26  63]]
              precision    recall  f1-score   support

           0       0.89      0.68      0.77       320
           1       0.38      0.71      0.49        89

    accuracy                           0.68       409
   macro avg       0.64      0.69      0.63       409
weighted avg       0.78      0.68      0.71       409

LightGBM
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).


/home/subbainria/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[[219 101]
 [ 21  68]]
              precision    recall  f1-score   support

           0       0.91      0.68      0.78       320
           1       0.40      0.76      0.53        89

    accuracy                           0.70       409
   macro avg       0.66      0.72      0.65       409
weighted avg       0.80      0.70      0.73       409

Random Over-Sampling
Logistic Regression
[[223  97]
 [ 29  60]]
              precision    recall  f1-score   support

           0       0.88      0.70      0.78       320
           1       0.38      0.67      0.49        89

    accuracy                           0.69       409
   macro avg       0.63      0.69      0.63       409
weighted avg       0.78      0.69      0.72       409

LightGBM
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).


/home/subbainria/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[[237  83]
 [ 26  63]]
              precision    recall  f1-score   support

           0       0.90      0.74      0.81       320
           1       0.43      0.71      0.54        89

    accuracy                           0.73       409
   macro avg       0.67      0.72      0.67       409
weighted avg       0.80      0.73      0.75       409

Random Over-Sampling
Logistic Regression
[[228  92]
 [ 24  65]]
              precision    recall  f1-score   support

           0       0.90      0.71      0.80       320
           1       0.41      0.73      0.53        89

    accuracy                           0.72       409
   macro avg       0.66      0.72      0.66       409
weighted avg       0.80      0.72      0.74       409

LightGBM
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).


/home/subbainria/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[[240  80]
 [ 20  69]]
              precision    recall  f1-score   support

           0       0.92      0.75      0.83       320
           1       0.46      0.78      0.58        89

    accuracy                           0.76       409
   macro avg       0.69      0.76      0.70       409
weighted avg       0.82      0.76      0.77       409



# Text Features Results

In [14]:
y = np.array(data['Comment label'])
y = np.delete(y, [506, 2040], axis=0)
x = np.load('text_feat_clip.npy')
print(x.shape, y.shape)

(2047, 512) (2047,)


# No Sampling

In [15]:
kf = StratifiedKFold(n_splits=5, shuffle=True)
for train_index, test_index in kf.split(np.arange(x.shape[0]),y):
    #print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = x[train_index], x[test_index]
    y_train, y_test = y[train_index], y[test_index]
    print('Logistic Regression')
    LR(X_train,X_test,y_train,y_test)
    print('LightGBM')
    LGBM(X_train,X_test,y_train,y_test)

Logistic Regression
[[200  35]
 [ 39 136]]
              precision    recall  f1-score   support

           0       0.84      0.85      0.84       235
           1       0.80      0.78      0.79       175

    accuracy                           0.82       410
   macro avg       0.82      0.81      0.82       410
weighted avg       0.82      0.82      0.82       410

LightGBM
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).


/home/subbainria/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[[206  29]
 [ 52 123]]
              precision    recall  f1-score   support

           0       0.80      0.88      0.84       235
           1       0.81      0.70      0.75       175

    accuracy                           0.80       410
   macro avg       0.80      0.79      0.79       410
weighted avg       0.80      0.80      0.80       410

Logistic Regression
[[192  43]
 [ 45 130]]
              precision    recall  f1-score   support

           0       0.81      0.82      0.81       235
           1       0.75      0.74      0.75       175

    accuracy                           0.79       410
   macro avg       0.78      0.78      0.78       410
weighted avg       0.79      0.79      0.79       410

LightGBM
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).


/home/subbainria/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[[200  35]
 [ 55 120]]
              precision    recall  f1-score   support

           0       0.78      0.85      0.82       235
           1       0.77      0.69      0.73       175

    accuracy                           0.78       410
   macro avg       0.78      0.77      0.77       410
weighted avg       0.78      0.78      0.78       410

Logistic Regression
[[197  38]
 [ 51 123]]
              precision    recall  f1-score   support

           0       0.79      0.84      0.82       235
           1       0.76      0.71      0.73       174

    accuracy                           0.78       409
   macro avg       0.78      0.77      0.78       409
weighted avg       0.78      0.78      0.78       409

LightGBM
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).


/home/subbainria/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[[201  34]
 [ 54 120]]
              precision    recall  f1-score   support

           0       0.79      0.86      0.82       235
           1       0.78      0.69      0.73       174

    accuracy                           0.78       409
   macro avg       0.78      0.77      0.78       409
weighted avg       0.78      0.78      0.78       409

Logistic Regression
[[200  35]
 [ 38 136]]
              precision    recall  f1-score   support

           0       0.84      0.85      0.85       235
           1       0.80      0.78      0.79       174

    accuracy                           0.82       409
   macro avg       0.82      0.82      0.82       409
weighted avg       0.82      0.82      0.82       409

LightGBM
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).


/home/subbainria/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[[209  26]
 [ 44 130]]
              precision    recall  f1-score   support

           0       0.83      0.89      0.86       235
           1       0.83      0.75      0.79       174

    accuracy                           0.83       409
   macro avg       0.83      0.82      0.82       409
weighted avg       0.83      0.83      0.83       409

Logistic Regression
[[198  37]
 [ 47 127]]
              precision    recall  f1-score   support

           0       0.81      0.84      0.83       235
           1       0.77      0.73      0.75       174

    accuracy                           0.79       409
   macro avg       0.79      0.79      0.79       409
weighted avg       0.79      0.79      0.79       409

LightGBM
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).


/home/subbainria/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[[209  26]
 [ 48 126]]
              precision    recall  f1-score   support

           0       0.81      0.89      0.85       235
           1       0.83      0.72      0.77       174

    accuracy                           0.82       409
   macro avg       0.82      0.81      0.81       409
weighted avg       0.82      0.82      0.82       409



# Over Sampling

In [16]:
for train_index, test_index in kf.split(np.arange(x.shape[0]),y):
    #print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = x[train_index], x[test_index]
    Y_train, Y_test = y[train_index], y[test_index]
    print('Random Over-Sampling')
    ros = RandomOverSampler()
    X_ros, y_ros = ros.fit_resample(X_train, Y_train)
    print('Logistic Regression')
    LR(X_ros,X_test,y_ros,Y_test)
    print('LightGBM')
    LGBM(X_ros,X_test,y_ros,Y_test)

Random Over-Sampling
Logistic Regression
[[196  39]
 [ 35 140]]
              precision    recall  f1-score   support

           0       0.85      0.83      0.84       235
           1       0.78      0.80      0.79       175

    accuracy                           0.82       410
   macro avg       0.82      0.82      0.82       410
weighted avg       0.82      0.82      0.82       410

LightGBM
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).


/home/subbainria/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[[211  24]
 [ 40 135]]
              precision    recall  f1-score   support

           0       0.84      0.90      0.87       235
           1       0.85      0.77      0.81       175

    accuracy                           0.84       410
   macro avg       0.84      0.83      0.84       410
weighted avg       0.84      0.84      0.84       410

Random Over-Sampling
Logistic Regression
[[203  32]
 [ 36 139]]
              precision    recall  f1-score   support

           0       0.85      0.86      0.86       235
           1       0.81      0.79      0.80       175

    accuracy                           0.83       410
   macro avg       0.83      0.83      0.83       410
weighted avg       0.83      0.83      0.83       410

LightGBM
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).


/home/subbainria/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[[216  19]
 [ 53 122]]
              precision    recall  f1-score   support

           0       0.80      0.92      0.86       235
           1       0.87      0.70      0.77       175

    accuracy                           0.82       410
   macro avg       0.83      0.81      0.81       410
weighted avg       0.83      0.82      0.82       410

Random Over-Sampling
Logistic Regression
[[190  45]
 [ 37 137]]
              precision    recall  f1-score   support

           0       0.84      0.81      0.82       235
           1       0.75      0.79      0.77       174

    accuracy                           0.80       409
   macro avg       0.79      0.80      0.80       409
weighted avg       0.80      0.80      0.80       409

LightGBM
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).


/home/subbainria/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[[199  36]
 [ 54 120]]
              precision    recall  f1-score   support

           0       0.79      0.85      0.82       235
           1       0.77      0.69      0.73       174

    accuracy                           0.78       409
   macro avg       0.78      0.77      0.77       409
weighted avg       0.78      0.78      0.78       409

Random Over-Sampling
Logistic Regression
[[182  53]
 [ 37 137]]
              precision    recall  f1-score   support

           0       0.83      0.77      0.80       235
           1       0.72      0.79      0.75       174

    accuracy                           0.78       409
   macro avg       0.78      0.78      0.78       409
weighted avg       0.78      0.78      0.78       409

LightGBM
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).


/home/subbainria/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[[196  39]
 [ 49 125]]
              precision    recall  f1-score   support

           0       0.80      0.83      0.82       235
           1       0.76      0.72      0.74       174

    accuracy                           0.78       409
   macro avg       0.78      0.78      0.78       409
weighted avg       0.78      0.78      0.78       409

Random Over-Sampling
Logistic Regression
[[190  45]
 [ 43 131]]
              precision    recall  f1-score   support

           0       0.82      0.81      0.81       235
           1       0.74      0.75      0.75       174

    accuracy                           0.78       409
   macro avg       0.78      0.78      0.78       409
weighted avg       0.79      0.78      0.78       409

LightGBM
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).


/home/subbainria/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[[199  36]
 [ 46 128]]
              precision    recall  f1-score   support

           0       0.81      0.85      0.83       235
           1       0.78      0.74      0.76       174

    accuracy                           0.80       409
   macro avg       0.80      0.79      0.79       409
weighted avg       0.80      0.80      0.80       409



# Under Sampling

In [17]:
for train_index, test_index in kf.split(np.arange(x.shape[0]),y):
    #print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = x[train_index], x[test_index]
    Y_train, Y_test = y[train_index], y[test_index]
    print('Random Over-Sampling')
    ros = RandomUnderSampler()
    X_ros, y_ros = ros.fit_resample(X_train, Y_train)
    print('Logistic Regression')
    LR(X_ros,X_test,y_ros,Y_test)
    print('LightGBM')
    LGBM(X_ros,X_test,y_ros,Y_test)

Random Over-Sampling
Logistic Regression
[[180  55]
 [ 53 122]]
              precision    recall  f1-score   support

           0       0.77      0.77      0.77       235
           1       0.69      0.70      0.69       175

    accuracy                           0.74       410
   macro avg       0.73      0.73      0.73       410
weighted avg       0.74      0.74      0.74       410

LightGBM
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).


/home/subbainria/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[[192  43]
 [ 58 117]]
              precision    recall  f1-score   support

           0       0.77      0.82      0.79       235
           1       0.73      0.67      0.70       175

    accuracy                           0.75       410
   macro avg       0.75      0.74      0.75       410
weighted avg       0.75      0.75      0.75       410

Random Over-Sampling
Logistic Regression
[[192  43]
 [ 35 140]]
              precision    recall  f1-score   support

           0       0.85      0.82      0.83       235
           1       0.77      0.80      0.78       175

    accuracy                           0.81       410
   macro avg       0.81      0.81      0.81       410
weighted avg       0.81      0.81      0.81       410

LightGBM
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).


/home/subbainria/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[[195  40]
 [ 40 135]]
              precision    recall  f1-score   support

           0       0.83      0.83      0.83       235
           1       0.77      0.77      0.77       175

    accuracy                           0.80       410
   macro avg       0.80      0.80      0.80       410
weighted avg       0.80      0.80      0.80       410

Random Over-Sampling
Logistic Regression
[[190  45]
 [ 31 143]]
              precision    recall  f1-score   support

           0       0.86      0.81      0.83       235
           1       0.76      0.82      0.79       174

    accuracy                           0.81       409
   macro avg       0.81      0.82      0.81       409
weighted avg       0.82      0.81      0.81       409

LightGBM
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).


/home/subbainria/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[[191  44]
 [ 32 142]]
              precision    recall  f1-score   support

           0       0.86      0.81      0.83       235
           1       0.76      0.82      0.79       174

    accuracy                           0.81       409
   macro avg       0.81      0.81      0.81       409
weighted avg       0.82      0.81      0.81       409

Random Over-Sampling
Logistic Regression
[[197  38]
 [ 32 142]]
              precision    recall  f1-score   support

           0       0.86      0.84      0.85       235
           1       0.79      0.82      0.80       174

    accuracy                           0.83       409
   macro avg       0.82      0.83      0.83       409
weighted avg       0.83      0.83      0.83       409

LightGBM
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).


/home/subbainria/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[[198  37]
 [ 42 132]]
              precision    recall  f1-score   support

           0       0.82      0.84      0.83       235
           1       0.78      0.76      0.77       174

    accuracy                           0.81       409
   macro avg       0.80      0.80      0.80       409
weighted avg       0.81      0.81      0.81       409

Random Over-Sampling
Logistic Regression
[[180  55]
 [ 34 140]]
              precision    recall  f1-score   support

           0       0.84      0.77      0.80       235
           1       0.72      0.80      0.76       174

    accuracy                           0.78       409
   macro avg       0.78      0.79      0.78       409
weighted avg       0.79      0.78      0.78       409

LightGBM
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).


/home/subbainria/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[[197  38]
 [ 37 137]]
              precision    recall  f1-score   support

           0       0.84      0.84      0.84       235
           1       0.78      0.79      0.79       174

    accuracy                           0.82       409
   macro avg       0.81      0.81      0.81       409
weighted avg       0.82      0.82      0.82       409



# Combined Image + Text dataset

In [18]:
img_features = np.load('img_feat_clip.npy')
text_features = np.load('text_feat_clip.npy')
x = np.concatenate([img_features, text_features], axis=1)
print(x.shape)

(2047, 1024)


In [19]:
combined = np.array(data['Combined label'])
y = np.delete(combined, [506, 2040], axis=0)
print(y.shape)

(2047,)


# No Sampling

In [20]:
kf = StratifiedKFold(n_splits=5, shuffle=True)
for train_index, test_index in kf.split(np.arange(x.shape[0]),y):
    #print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = x[train_index], x[test_index]
    y_train, y_test = y[train_index], y[test_index]
    print('Logistic Regression')
    LR(X_train,X_test,y_train,y_test)
    print('LightGBM')
    LGBM(X_train,X_test,y_train,y_test)

Logistic Regression
[[ 76  46]
 [ 53 235]]
              precision    recall  f1-score   support

           0       0.59      0.62      0.61       122
           1       0.84      0.82      0.83       288

    accuracy                           0.76       410
   macro avg       0.71      0.72      0.72       410
weighted avg       0.76      0.76      0.76       410

LightGBM
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).


/home/subbainria/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[[ 58  64]
 [ 21 267]]
              precision    recall  f1-score   support

           0       0.73      0.48      0.58       122
           1       0.81      0.93      0.86       288

    accuracy                           0.79       410
   macro avg       0.77      0.70      0.72       410
weighted avg       0.79      0.79      0.78       410

Logistic Regression
[[ 61  61]
 [ 38 250]]
              precision    recall  f1-score   support

           0       0.62      0.50      0.55       122
           1       0.80      0.87      0.83       288

    accuracy                           0.76       410
   macro avg       0.71      0.68      0.69       410
weighted avg       0.75      0.76      0.75       410

LightGBM
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).


/home/subbainria/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[[ 48  74]
 [ 15 273]]
              precision    recall  f1-score   support

           0       0.76      0.39      0.52       122
           1       0.79      0.95      0.86       288

    accuracy                           0.78       410
   macro avg       0.77      0.67      0.69       410
weighted avg       0.78      0.78      0.76       410

Logistic Regression
[[ 68  54]
 [ 36 251]]
              precision    recall  f1-score   support

           0       0.65      0.56      0.60       122
           1       0.82      0.87      0.85       287

    accuracy                           0.78       409
   macro avg       0.74      0.72      0.72       409
weighted avg       0.77      0.78      0.77       409

LightGBM
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).


/home/subbainria/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[[ 54  68]
 [ 19 268]]
              precision    recall  f1-score   support

           0       0.74      0.44      0.55       122
           1       0.80      0.93      0.86       287

    accuracy                           0.79       409
   macro avg       0.77      0.69      0.71       409
weighted avg       0.78      0.79      0.77       409

Logistic Regression
[[ 68  54]
 [ 48 239]]
              precision    recall  f1-score   support

           0       0.59      0.56      0.57       122
           1       0.82      0.83      0.82       287

    accuracy                           0.75       409
   macro avg       0.70      0.70      0.70       409
weighted avg       0.75      0.75      0.75       409

LightGBM
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).


/home/subbainria/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[[ 59  63]
 [ 25 262]]
              precision    recall  f1-score   support

           0       0.70      0.48      0.57       122
           1       0.81      0.91      0.86       287

    accuracy                           0.78       409
   macro avg       0.75      0.70      0.71       409
weighted avg       0.78      0.78      0.77       409

Logistic Regression
[[ 67  55]
 [ 42 245]]
              precision    recall  f1-score   support

           0       0.61      0.55      0.58       122
           1       0.82      0.85      0.83       287

    accuracy                           0.76       409
   macro avg       0.72      0.70      0.71       409
weighted avg       0.76      0.76      0.76       409

LightGBM
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).


/home/subbainria/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[[ 65  57]
 [ 19 268]]
              precision    recall  f1-score   support

           0       0.77      0.53      0.63       122
           1       0.82      0.93      0.88       287

    accuracy                           0.81       409
   macro avg       0.80      0.73      0.75       409
weighted avg       0.81      0.81      0.80       409



# Over-Sampling

In [21]:
for train_index, test_index in kf.split(np.arange(x.shape[0]),y):
    #print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = x[train_index], x[test_index]
    Y_train, Y_test = y[train_index], y[test_index]
    print('Random Over-Sampling')
    ros = RandomOverSampler()
    X_ros, y_ros = ros.fit_resample(X_train, Y_train)
    print('Logistic Regression')
    LR(X_ros,X_test,y_ros,Y_test)
    print('LightGBM')
    LGBM(X_ros,X_test,y_ros,Y_test)

Random Over-Sampling
Logistic Regression
[[ 66  56]
 [ 58 230]]
              precision    recall  f1-score   support

           0       0.53      0.54      0.54       122
           1       0.80      0.80      0.80       288

    accuracy                           0.72       410
   macro avg       0.67      0.67      0.67       410
weighted avg       0.72      0.72      0.72       410

LightGBM
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).


/home/subbainria/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[[ 55  67]
 [ 26 262]]
              precision    recall  f1-score   support

           0       0.68      0.45      0.54       122
           1       0.80      0.91      0.85       288

    accuracy                           0.77       410
   macro avg       0.74      0.68      0.70       410
weighted avg       0.76      0.77      0.76       410

Random Over-Sampling
Logistic Regression
[[ 75  47]
 [ 55 233]]
              precision    recall  f1-score   support

           0       0.58      0.61      0.60       122
           1       0.83      0.81      0.82       288

    accuracy                           0.75       410
   macro avg       0.70      0.71      0.71       410
weighted avg       0.76      0.75      0.75       410

LightGBM
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).


/home/subbainria/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[[ 67  55]
 [ 12 276]]
              precision    recall  f1-score   support

           0       0.85      0.55      0.67       122
           1       0.83      0.96      0.89       288

    accuracy                           0.84       410
   macro avg       0.84      0.75      0.78       410
weighted avg       0.84      0.84      0.82       410

Random Over-Sampling
Logistic Regression
[[ 73  49]
 [ 42 245]]
              precision    recall  f1-score   support

           0       0.63      0.60      0.62       122
           1       0.83      0.85      0.84       287

    accuracy                           0.78       409
   macro avg       0.73      0.73      0.73       409
weighted avg       0.77      0.78      0.78       409

LightGBM
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).


/home/subbainria/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[[ 56  66]
 [ 22 265]]
              precision    recall  f1-score   support

           0       0.72      0.46      0.56       122
           1       0.80      0.92      0.86       287

    accuracy                           0.78       409
   macro avg       0.76      0.69      0.71       409
weighted avg       0.78      0.78      0.77       409

Random Over-Sampling
Logistic Regression
[[ 68  54]
 [ 67 220]]
              precision    recall  f1-score   support

           0       0.50      0.56      0.53       122
           1       0.80      0.77      0.78       287

    accuracy                           0.70       409
   macro avg       0.65      0.66      0.66       409
weighted avg       0.71      0.70      0.71       409

LightGBM
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).


/home/subbainria/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[[ 56  66]
 [ 36 251]]
              precision    recall  f1-score   support

           0       0.61      0.46      0.52       122
           1       0.79      0.87      0.83       287

    accuracy                           0.75       409
   macro avg       0.70      0.67      0.68       409
weighted avg       0.74      0.75      0.74       409

Random Over-Sampling
Logistic Regression
[[ 78  44]
 [ 74 213]]
              precision    recall  f1-score   support

           0       0.51      0.64      0.57       122
           1       0.83      0.74      0.78       287

    accuracy                           0.71       409
   macro avg       0.67      0.69      0.68       409
weighted avg       0.73      0.71      0.72       409

LightGBM
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).


/home/subbainria/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[[ 63  59]
 [ 27 260]]
              precision    recall  f1-score   support

           0       0.70      0.52      0.59       122
           1       0.82      0.91      0.86       287

    accuracy                           0.79       409
   macro avg       0.76      0.71      0.73       409
weighted avg       0.78      0.79      0.78       409



# Under-Sampling

In [22]:
for train_index, test_index in kf.split(np.arange(x.shape[0]),y):
    #print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = x[train_index], x[test_index]
    Y_train, Y_test = y[train_index], y[test_index]
    print('Random Over-Sampling')
    ros = RandomUnderSampler()
    X_ros, y_ros = ros.fit_resample(X_train, Y_train)
    print('Logistic Regression')
    LR(X_ros,X_test,y_ros,Y_test)
    print('LightGBM')
    LGBM(X_ros,X_test,y_ros,Y_test)

Random Over-Sampling
Logistic Regression
[[ 96  26]
 [ 93 195]]
              precision    recall  f1-score   support

           0       0.51      0.79      0.62       122
           1       0.88      0.68      0.77       288

    accuracy                           0.71       410
   macro avg       0.70      0.73      0.69       410
weighted avg       0.77      0.71      0.72       410

LightGBM
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).


/home/subbainria/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[[ 93  29]
 [ 71 217]]
              precision    recall  f1-score   support

           0       0.57      0.76      0.65       122
           1       0.88      0.75      0.81       288

    accuracy                           0.76       410
   macro avg       0.72      0.76      0.73       410
weighted avg       0.79      0.76      0.76       410

Random Over-Sampling
Logistic Regression
[[ 80  42]
 [ 87 201]]
              precision    recall  f1-score   support

           0       0.48      0.66      0.55       122
           1       0.83      0.70      0.76       288

    accuracy                           0.69       410
   macro avg       0.65      0.68      0.66       410
weighted avg       0.72      0.69      0.70       410

LightGBM
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).


/home/subbainria/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[[ 87  35]
 [ 66 222]]
              precision    recall  f1-score   support

           0       0.57      0.71      0.63       122
           1       0.86      0.77      0.81       288

    accuracy                           0.75       410
   macro avg       0.72      0.74      0.72       410
weighted avg       0.78      0.75      0.76       410

Random Over-Sampling
Logistic Regression
[[ 85  37]
 [ 80 207]]
              precision    recall  f1-score   support

           0       0.52      0.70      0.59       122
           1       0.85      0.72      0.78       287

    accuracy                           0.71       409
   macro avg       0.68      0.71      0.69       409
weighted avg       0.75      0.71      0.72       409

LightGBM
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).


/home/subbainria/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[[ 87  35]
 [ 74 213]]
              precision    recall  f1-score   support

           0       0.54      0.71      0.61       122
           1       0.86      0.74      0.80       287

    accuracy                           0.73       409
   macro avg       0.70      0.73      0.71       409
weighted avg       0.76      0.73      0.74       409

Random Over-Sampling
Logistic Regression
[[ 88  34]
 [ 78 209]]
              precision    recall  f1-score   support

           0       0.53      0.72      0.61       122
           1       0.86      0.73      0.79       287

    accuracy                           0.73       409
   macro avg       0.70      0.72      0.70       409
weighted avg       0.76      0.73      0.74       409

LightGBM
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).


/home/subbainria/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[[ 85  37]
 [ 66 221]]
              precision    recall  f1-score   support

           0       0.56      0.70      0.62       122
           1       0.86      0.77      0.81       287

    accuracy                           0.75       409
   macro avg       0.71      0.73      0.72       409
weighted avg       0.77      0.75      0.75       409

Random Over-Sampling
Logistic Regression
[[ 95  27]
 [ 79 208]]
              precision    recall  f1-score   support

           0       0.55      0.78      0.64       122
           1       0.89      0.72      0.80       287

    accuracy                           0.74       409
   macro avg       0.72      0.75      0.72       409
weighted avg       0.78      0.74      0.75       409

LightGBM
[LightGBM] [Warning] Accuracy may be bad since you didn't explicitly set num_leaves OR 2^max_depth > num_leaves. (num_leaves=31).


/home/subbainria/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[[ 97  25]
 [ 74 213]]
              precision    recall  f1-score   support

           0       0.57      0.80      0.66       122
           1       0.89      0.74      0.81       287

    accuracy                           0.76       409
   macro avg       0.73      0.77      0.74       409
weighted avg       0.80      0.76      0.77       409



In [23]:
data['Combined label'].value_counts()

1    1439
0     610
Name: Combined label, dtype: int64

In [24]:
data['Imagelabel'].value_counts()

0    1603
1     446
Name: Imagelabel, dtype: int64

In [25]:
data['Comment label'].value_counts()

0    1176
1     873
Name: Comment label, dtype: int64

In [26]:
data.columns

Index(['Imageid', 'Imagelabel', 'Comment', 'Comment label', 'Combined label'], dtype='object')